version: 2.1

jobs:
  build_and_test:
    docker:
      - image: openjdk:8-jdk-alpine
    steps:
      - checkout
      - run: ./gradlew build
      - store_test_results:
          path: build/test-results

workflows:
  version: 2
  spring_boot_Scheduler_cicd_workflow:
    jobs:
      - build_and_test